-- 1. Tabela Regiao
CREATE TABLE "Regiao" (
    "ID_REGIAO" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "NOME_REGIAO" VARCHAR(50) NOT NULL,
    "POPULACAO_TOTAL" INT,
    "POPULACAO_INDIGENA" INT
);

-- 2. Tabela Unidade_Federativa
CREATE TABLE "Unidade_Federativa" (
    "ID_UF" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "NOME_UF" VARCHAR(50) NOT NULL,
    "SIGLA_UF" CHAR(2) NOT NULL,
    "ID_REGIAO" INT NOT NULL,
    "POPULACAO_TOTAL" INT,
    "POPULACAO_INDIGENA" INT,
    FOREIGN KEY ("ID_REGIAO") REFERENCES "Regiao"("ID_REGIAO")
);

-- 3. Tabela Municipio
CREATE TABLE "Municipio" (
    "ID_MUNICIPIO" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "NOME_MUNICIPIO" VARCHAR(100) NOT NULL,
    "ID_UF" INT NOT NULL,
    "POPULACAO_TOTAL" INT,
    "POPULACAO_INDIGENA" INT,
    FOREIGN KEY ("ID_UF") REFERENCES "Unidade_Federativa"("ID_UF")
);

-- 4. Tabela Escola (VARCHAR sem CHECK)
CREATE TABLE "Escola" (
    "ID_ESCOLA" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "NOME_ESCOLA" VARCHAR(100) NOT NULL,
    "ID_MUNICIPIO" INT NOT NULL,
    "TIPO_DEPENDENCIA" VARCHAR(20) NOT NULL, -- Federal/Estadual/Municipal/Privada
    "TIPO_LOCALIZACAO" VARCHAR(20) NOT NULL, -- Urbana/Rural
    "SITUACAO_FUNCIONAMENTO" VARCHAR(20) NOT NULL DEFAULT 'Ativa', -- Ativa/Inativa
    "INDIGENA" BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY ("ID_MUNICIPIO") REFERENCES "Municipio"("ID_MUNICIPIO")
);

-- 5. Tabela Turma (VARCHAR sem CHECK)
CREATE TABLE "Turma" (
    "ID_TURMA" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_ESCOLA" INT NOT NULL,
    "NIVEL_ENSINO" VARCHAR(20) NOT NULL, -- Infantil/Fundamental/Medio/EJA
    "QT_TURMAS" INT NOT NULL DEFAULT 0,
    "QT_TURMAS_INDIGENAS" INT DEFAULT 0,
    FOREIGN KEY ("ID_ESCOLA") REFERENCES "Escola"("ID_ESCOLA")
);

-- 6. Tabela Matricula (VARCHAR sem CHECK)
CREATE TABLE "Matricula" (
    "ID_MATRICULA" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_ESCOLA" INT NOT NULL,
    "NIVEL_ENSINO" VARCHAR(20) NOT NULL, -- Infantil/Fundamental/Medio/EJA
    "QT_MATRICULAS_TOTAL" INT NOT NULL DEFAULT 0,
    "QT_MATRICULAS_INDIGENAS" INT DEFAULT 0,
    "ANO_REFERENCIA" INT NOT NULL,
    FOREIGN KEY ("ID_ESCOLA") REFERENCES "Escola"("ID_ESCOLA")
);

-- 7. Tabela Frequencia_Escolar
CREATE TABLE "Frequencia_Escolar" (
    "ID_FREQUENCIA" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_MUNICIPIO" INT NOT NULL,
    "FAIXA_ETARIA" VARCHAR(20) NOT NULL,
    "TAXA_FREQUENCIA" DECIMAL(5,2) NOT NULL,
    FOREIGN KEY ("ID_MUNICIPIO") REFERENCES "Municipio"("ID_MUNICIPIO"),
    CONSTRAINT "check_taxa_frequencia" CHECK ("TAXA_FREQUENCIA" BETWEEN 0 AND 100)
);


-- 8. Tabela Nivel_Instrucao (VARCHAR sem CHECK)
CREATE TABLE "Nivel_Instrucao" (
    "ID_NIVEL_INSTRUCAO" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_MUNICIPIO" INT NOT NULL,
    "FAIXA_ETARIA" VARCHAR(20) NOT NULL,
    "NIVEL" VARCHAR(30) NOT NULL, -- Sem instrução/Fundamental incompleto/etc
    "QT_PESSOAS" INT NOT NULL DEFAULT 0,
    FOREIGN KEY ("ID_MUNICIPIO") REFERENCES "Municipio"("ID_MUNICIPIO")
);


-- 9. Tabela Anos_Estudo
CREATE TABLE "Anos_Estudo" (
    "ID_ANOS_ESTUDO" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_MUNICIPIO" INT NOT NULL,
    "FAIXA_ETARIA" VARCHAR(20) NOT NULL,
    "MEDIA_ANOS_ESTUDO" DECIMAL(3,1) NOT NULL,
    FOREIGN KEY ("ID_MUNICIPIO") REFERENCES "Municipio"("ID_MUNICIPIO"),
    CONSTRAINT "check_media_anos" CHECK ("MEDIA_ANOS_ESTUDO" BETWEEN 0 AND 20)
);

-- 10. Tabela Territorio_Indigena
CREATE TABLE "Territorio_Indigena" (
    "ID_TERRITORIO" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_UF" INT NOT NULL,
    "NOME_TERRITORIO" VARCHAR(100) NOT NULL,
    "ETNIA_DOMINANTE" VARCHAR(50),
    "AREA" DECIMAL(12,2),
    "POP_TOTAL" INT,
    FOREIGN KEY ("ID_UF") REFERENCES "Unidade_Federativa"("ID_UF"),
    CONSTRAINT "check_area" CHECK ("AREA" >= 0),
    CONSTRAINT "check_pop_total" CHECK ("POP_TOTAL" >= 0)
);

